'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Cargo

    '''<summary>
    '''SqlDS_CargoList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDS_CargoList As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''updtPan_CargoList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updtPan_CargoList As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''pan_CargoList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pan_CargoList As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''btn_PrintViewCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_PrintViewCargo As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ucFromCalendar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucFromCalendar As Global.MJBUMAC1.Calendar

    '''<summary>
    '''ucToCalendar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucToCalendar As Global.MJBUMAC1.Calendar

    '''<summary>
    '''drp_CargoStatusFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drp_CargoStatusFilter As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btn_FilterCargoList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_FilterCargoList As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txt_SearchCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_SearchCargo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_SearchCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_SearchCargo As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''grdViewCargoList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdViewCargoList As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lbl_Total control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Total As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btn_ExportCargotoExcel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_ExportCargotoExcel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''updtPan_CargoPrintSchedule control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updtPan_CargoPrintSchedule As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''pan_ViewPrintSchedule control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pan_ViewPrintSchedule As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_MsgCargoPickupSched control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_MsgCargoPickupSched As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SqlDS_PrintViewSchedulePickup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDS_PrintViewSchedulePickup As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''tbl_CargoHeaderPickUpList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbl_CargoHeaderPickUpList As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''lbl_Address control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Address As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_SelectedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_SelectedDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_Location control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Location As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''grdViewSchedulePickupList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdViewSchedulePickupList As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lbl_TotalCargoSched control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_TotalCargoSched As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pan_ViewPrintPickupSched control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pan_ViewPrintPickupSched As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''updtPan_ViewPrintPickupSched control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updtPan_ViewPrintPickupSched As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''pan_HeadTitlePrintPickupSched control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pan_HeadTitlePrintPickupSched As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pan_CargoPickUpSchedule control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pan_CargoPickUpSchedule As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''UcCalendarSelectDateCargoPickupDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UcCalendarSelectDateCargoPickupDate As Global.MJBUMAC1.Calendar

    '''<summary>
    '''btn_EditCargoSched control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_EditCargoSched As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''drp_SelectLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drp_SelectLocation As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btn_PrintViewCargoSched control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_PrintViewCargoSched As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pan_UpdateCargoSchedule control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pan_UpdateCargoSchedule As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_MsgCargoEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_MsgCargoEdit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SqlDS_UpdateCargoSchedule control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDS_UpdateCargoSchedule As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''grdViewUpdateCargoSchedlue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdViewUpdateCargoSchedlue As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lbl_TotalCargoPickupUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_TotalCargoPickupUpdate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pan_CargoEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pan_CargoEdit As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''updtPan_CargoEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updtPan_CargoEdit As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''pan_HeadTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pan_HeadTitle As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_HeaderCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_HeaderCargo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_ServiceID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_ServiceID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pan_CargoAddUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pan_CargoAddUpdate As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txt_SenderName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_SenderName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''hdn_SenderID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdn_SenderID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdn_RecipientID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdn_RecipientID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdn_IDNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdn_IDNum As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''drp_RecipientName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drp_RecipientName As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''RequiredFieldValidator1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator1 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txt_CtrlNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_CtrlNumber As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RequiredFieldValidator2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator2 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txt_BoxNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_BoxNumber As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RequiredFieldValidator3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator3 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txt_ServiceCharge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_ServiceCharge As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RequiredFieldValidator4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator4 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''RegularExpressionValidator1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RegularExpressionValidator1 As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''txt_AgentCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_AgentCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RequiredFieldValidator6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator6 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''ucServiceDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucServiceDate As Global.MJBUMAC1.REQCalendar

    '''<summary>
    '''txt_NewNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_NewNotes As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_DeleteCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_DeleteCargo As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_AddUpdateCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_AddUpdateCargo As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbl_MsgCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_MsgCargo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ConfirmExt_DeleteCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ConfirmExt_DeleteCargo As Global.AjaxControlToolkit.ConfirmButtonExtender

    '''<summary>
    '''lbl_ConfirmMessageOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_ConfirmMessageOK As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btn_ConfirmOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_ConfirmOK As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_AddMore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_AddMore As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''UpdateProgress1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdateProgress1 As Global.System.Web.UI.UpdateProgress
End Class
