'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Customer

    '''<summary>
    '''SqlDS_CustomerList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDS_CustomerList As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sqlDS_SearchRecipient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlDS_SearchRecipient As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''updtPan_CustomerList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updtPan_CustomerList As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lbl_SubHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_SubHeader As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_SearchCustomer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_SearchCustomer As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''drp_SearchCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drp_SearchCategory As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btn_SearchCustomer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_SearchCustomer As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_AddNewCustomer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_AddNewCustomer As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pan_CustomerList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pan_CustomerList As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''grdViewCustomerList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdViewCustomerList As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lbl_Total control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Total As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pan_RecipientList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pan_RecipientList As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''grdViewSearchRecipientList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdViewSearchRecipientList As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''updtPan_CustomerPrintView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updtPan_CustomerPrintView As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''pan_CustomerPrintView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pan_CustomerPrintView As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_FirstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_FirstName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_LastName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_LastName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_Address1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Address1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_Address2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Address2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_City control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_City As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_State control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_State As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_Zip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Zip As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_Country control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Country As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_Phone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Phone As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_AltPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_AltPhone As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_ID1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_ID1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_ID2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_ID2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_Notes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Notes As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_AddressNotesP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_AddressNotesP As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pan_CustomerRecipientEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pan_CustomerRecipientEdit As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''updtPan_CustomerRecipientEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updtPan_CustomerRecipientEdit As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''pan_HeadTitleRecipient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pan_HeadTitleRecipient As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_CustomerName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_CustomerName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hdn_SenderID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdn_SenderID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''pan_CustomerRecipientInfoList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pan_CustomerRecipientInfoList As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''btn_AddNewRecipient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_AddNewRecipient As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''SqlDS_Recipient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDS_Recipient As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''grdViewRecipientList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdViewRecipientList As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lbl_TotalRecipient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_TotalRecipient As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pan_AddUpdateRecipient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pan_AddUpdateRecipient As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_RecipientAddUpdateHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_RecipientAddUpdateHeader As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hdn_RecipientID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdn_RecipientID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txt_RecipientFirst control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_RecipientFirst As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''reqFieldRecipient1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqFieldRecipient1 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txt_RecipientLast control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_RecipientLast As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''reqFieldRecipient2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqFieldRecipient2 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txt_RecipientAddress1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_RecipientAddress1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''reqFieldRecipient3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqFieldRecipient3 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txt_RecipientAddress2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_RecipientAddress2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_RecipientCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_RecipientCity As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''reqFieldRecipient4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqFieldRecipient4 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txt_RecipientStateProvince control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_RecipientStateProvince As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_RecipientZip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_RecipientZip As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_RecipientCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_RecipientCountry As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_Recipientphone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Recipientphone As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_NewNotesRecipient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_NewNotesRecipient As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_DeleteRecipient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_DeleteRecipient As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_CancelEditRecipient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_CancelEditRecipient As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_AddUpdateRecipient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_AddUpdateRecipient As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbl_MsgErrRecipient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_MsgErrRecipient As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pan_RecipientHistoryAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pan_RecipientHistoryAddress As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_RecipientNameAddHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_RecipientNameAddHistory As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SqlDS_RecipientAddHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDS_RecipientAddHistory As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''grdViewRecipientAddressHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdViewRecipientAddressHistory As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''btn_CloseRecipientAddressHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_CloseRecipientAddressHistory As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbl_ConfirmMessageOKRecipient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_ConfirmMessageOKRecipient As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btn_ConfirmOKRecipient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_ConfirmOKRecipient As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_DeleteRecipientYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_DeleteRecipientYes As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_DeleteRecipientNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_DeleteRecipientNo As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pan_CustomerEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pan_CustomerEdit As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''updtPan_CustomerEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updtPan_CustomerEdit As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''pan_HeadTitleCustomer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pan_HeadTitleCustomer As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_CustomerAddUpdateHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_CustomerAddUpdateHeader As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hdn_CustomerEditID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdn_CustomerEditID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''pan_CustomerAddUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pan_CustomerAddUpdate As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txt_CustomerFirstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_CustomerFirstName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''reqFieldCustomer1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqFieldCustomer1 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txt_CustomerLastName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_CustomerLastName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''reqFieldCustomer2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqFieldCustomer2 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txt_CustomerAdd1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_CustomerAdd1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''reqFieldCustomer3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqFieldCustomer3 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txt_CustomerAdd2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_CustomerAdd2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_CustomerCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_CustomerCity As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''reqFieldCustomer4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqFieldCustomer4 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txt_CustomerState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_CustomerState As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''reqFieldCustomer5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqFieldCustomer5 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txt_CustomerZip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_CustomerZip As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''reqFieldCustomer6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqFieldCustomer6 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txt_CustomerCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_CustomerCountry As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_CustomerPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_CustomerPhone As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_CustomerAltPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_CustomerAltPhone As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_CustomerID1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_CustomerID1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_CustomerID2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_CustomerID2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_CustomerNewNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_CustomerNewNotes As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_AddressNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_AddressNotes As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_DeleteCustomer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_DeleteCustomer As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_PrintViewCustomer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_PrintViewCustomer As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_AddUpdateCustomer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_AddUpdateCustomer As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbl_ErrMsgCustomer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_ErrMsgCustomer As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_ConfirmMessageOKCustomer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_ConfirmMessageOKCustomer As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btn_ConfirmOKCustomer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_ConfirmOKCustomer As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_DeleteCustomerYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_DeleteCustomerYes As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_DeleteCustomerNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_DeleteCustomerNo As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pan_PickupCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pan_PickupCargo As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''updtPan_PickupCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updtPan_PickupCargo As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''pan_HeadTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pan_HeadTitle As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''hdn_SenderIDCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdn_SenderIDCargo As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdn_CargoPickupID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdn_CargoPickupID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''imgButtonAddNewCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgButtonAddNewCargo As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lbl_SenderName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_SenderName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pan_PickupCargoAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pan_PickupCargoAdd As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ucPickUpDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucPickUpDate As Global.MJBUMAC1.REQCalendarAutoPost

    '''<summary>
    '''drp_TripNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drp_TripNumber As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txt_PickupCargoNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_PickupCargoNotes As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''drp_CargoPickupStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drp_CargoPickupStatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btn_AddPickupCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_AddPickupCancel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_AddPickupCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_AddPickupCargo As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbl_MsgCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_MsgCargo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pan_PickupCargoUpdateMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pan_PickupCargoUpdateMsg As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_MsgAddUpdateCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_MsgAddUpdateCargo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btn_CargoAddUpdateOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_CargoAddUpdateOK As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pan_PickupCargoList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pan_PickupCargoList As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''SQLDS_PickUpCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SQLDS_PickUpCargo As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''grdViewCargoPickUpDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdViewCargoPickUpDate As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lbl_MsgCargo2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_MsgCargo2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''updtPan_CargoHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updtPan_CargoHistory As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''panCargoHistoryHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panCargoHistoryHeader As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pan_CargoHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pan_CargoHistory As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''SQLDS_HistoryCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SQLDS_HistoryCargo As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''grdview_CargoHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdview_CargoHistory As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lbl_CargoHistoryTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_CargoHistoryTotal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btn_PrintCargoHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_PrintCargoHistory As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Panel4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel4 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''updtPan_RecipientCargoHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updtPan_RecipientCargoHistory As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''pan_RecipientCargoHistoryHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pan_RecipientCargoHistoryHeader As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_RecipientNameCargoHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_RecipientNameCargoHistory As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pan_RecipientCargoHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pan_RecipientCargoHistory As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''SqlDS_RecipientCargoHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDS_RecipientCargoHistory As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''grdview_RecipientCargoHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdview_RecipientCargoHistory As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lbl_TotalRecipientCargorHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_TotalRecipientCargorHistory As Global.System.Web.UI.WebControls.Label
End Class
